import type { ComponentDefinition } from "@/types/builder";

export const availableComponentsList: ComponentDefinition[] = [
  {
    id: "",
    type: "text",
    label: "Text",
    props: {},
    defaultProps: {
      content: "New Text Block",
      fontSize: "16px",
      color: "#333",
      margin: "0",
      padding: "0",
      width: "auto",
      height: "auto",
    },
  },
  {
    id: "",
    props: {},
    type: "button",
    label: "Button",
    defaultProps: {
      text: "Click Me",
      backgroundColor: "#007bff",
      color: "#ffffff",
      margin: "0",
      padding: "0",
      width: "auto",
      height: "auto",
    },
  },
  {
    id: "",
    props: {},
    type: "image",
    label: "Image",
    defaultProps: {
      src: "https://placeholder.pics/svg/300",
      alt: "My Image",
      width: "auto",
      height: "auto",
      margin: "0",
      padding: "0",
    },
  },
  {
    id: "",
    props: {},
    type: "container",
    label: "Container",
    defaultProps: {
      padding: "0",
      margin: "0",
      backgroundColor: "rgba(200,200,200,0.1)",
      minHeight: "80px",
      name: "Row Container",
      flexDirection: "row",
      alignItems: "center",
      width: "auto",
      height: "auto",
    },
    children: [],
  },
  {
    id: "",
    props: {},
    type: "input",
    label: "Input",
    defaultProps: {
      kind: "text",
      margin: "0",
      padding: "0",
      width: "auto",
      height: "auto",
    },
  },
  {
    id: "",
    props: {},
    type: "icon",
    label: "Icon",
    defaultProps: {
      name: "Square",
      size: 24,
      color: "#111827",
      margin: "0",
      padding: "0",
    },
  },
];
